apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kube-job
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-job
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-job
    spec:
      containers:
      - name:  kube-job
        image:  kube-job:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8081
          name:  kube-job
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kube-svc
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32700
  selector:
    app: kube-job
